pub mod v1 {
    // `clippy::result_large_err` fires 20 times inside the code
    // `tonic::include_proto!` pastes in below (every generated client method
    // returns `Result<_, tonic::Status>`, and `tonic::Status` is ~176 bytes).
    // That file is REGENERATED by `build.rs` into `OUT_DIR` on every build, so
    // there is no source to annotate and no way to fix it here -- the lint is
    // about tonic's own return type, not about anything this repo wrote.
    // Allowed at the module rather than via a `tonic_build` `.attribute()` so
    // `build.rs` stays untouched.
    //
    // Scope note: this also covers the hand-written `impl ApplyDiff` below,
    // which is the small cost of putting the allow here. The same lint fires
    // 11 more times in `wiremesh-controller` on real source; those are NOT
    // covered by this and are handled on their own merits.
    #![allow(clippy::result_large_err)]

    tonic::include_proto!("wiremesh.v1");

    // (Task 14) `total_changes` already sums every diff field server-side
    // (see `admin.proto`'s `ApplyDiff` doc comment), so `is_empty()` is just
    // that check — kept as an inherent method (rather than making every
    // caller re-derive it) since a caller checking "was this apply a no-op"
    // is common (the idempotence contract `tests/apply.rs` exercises, and
    // `fabricctl apply`'s printed summary).
    impl ApplyDiff {
        pub fn is_empty(&self) -> bool {
            self.total_changes == 0
        }
    }
}
