pub mod v1 {
    // `clippy::result_large_err` on the code `tonic::include_proto!` pastes in
    // below: every generated client method returns `Result<_, tonic::Status>`,
    // and `tonic::Status` is ~176 bytes. The lint is about tonic's return type,
    // not about anything this repo wrote, and the file is REGENERATED by
    // `build.rs` into `OUT_DIR` on every build, so there is no source to
    // annotate. Allowed at the module rather than through a `tonic_build`
    // `.attribute()` so `build.rs` stays untouched.
    //
    // MEASURED, and the number depends on the toolchain -- which is why this
    // says so instead of quoting one count as if it were a property of the
    // code. Under the pinned `dev/Dockerfile` toolchain (clippy 0.1.97) this
    // lint does NOT fire on the generated file at all, so today this attribute
    // suppresses nothing here. Under clippy 0.1.98 it fires 20 times. It is
    // kept deliberately: the pin is expected to move, `-D warnings` makes those
    // 20 hard errors the day it does, and there is no source file to add the
    // allow to at that point either.
    //
    // Scope note: this also covers the hand-written `impl ApplyDiff` below,
    // which is the cost of putting the allow here. The same lint fires on real
    // `wiremesh-controller` source (5 sites under 0.1.97, 11 under 0.1.98);
    // those are NOT covered by this and are handled on their own merits.
    #![allow(clippy::result_large_err)]

    tonic::include_proto!("wiremesh.v1");

    // (Task 14) `total_changes` already sums every diff field server-side
    // (see `admin.proto`'s `ApplyDiff` doc comment), so `is_empty()` is just
    // that check — kept as an inherent method (rather than making every
    // caller re-derive it) since a caller checking "was this apply a no-op"
    // is common (the idempotence contract `tests/apply.rs` exercises, and
    // `fabricctl apply`'s printed summary).
    impl ApplyDiff {
        pub fn is_empty(&self) -> bool {
            self.total_changes == 0
        }
    }
}
