[package]
name = "enforcer-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
enforcer-common = { path = "../enforcer-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "enforcer"
path = "src/main.rs"
