#!/usr/bin/env bash
# dev/doctest-counts.sh — pin the per-crate doctest inventory.
#
# WHY THIS EXISTS. `cargo test --doc` exiting 0 proves the doctests that exist
# COMPILE AND PASS. It does not prove the same doctests exist. Both directions
# of drift are silent and both matter:
#
#   * ONE APPEARED. PR0b did this. A blank `///` inserted to satisfy
#     `doc_lazy_continuation` closed a Markdown list, which turned a
#     six-space-indented paragraph NINE LINES FURTHER DOWN -- untouched by the
#     edit -- into an indented code block. rustdoc compiles those, so a
#     paragraph of English became a doctest with 34 syntax errors. Five clippy
#     invocations and two `fmt --check`s were green over it, and a token-level
#     comparison of the doc text could not see it either: every token was
#     identical, only Markdown's INTERPRETATION moved.
#   * ONE VANISHED. A doctest deleted or accidentally fenced out is a LOST
#     TEST. Nothing else in CI notices; `--doc` still exits 0.
#
# Why a committed table rather than an A/B against the merge base: it costs no
# second workspace compile, it catches the case an A/B cannot (a doctest
# deleted upstream, where base and head agree and are both wrong), and changing
# the inventory becomes a DELIBERATE edit to a reviewed file instead of a
# number that drifts unobserved.
#
# The values in `dev/doctest-counts.txt` are MEASURED, never hand-written:
#   ./dev.sh run "cd /work && cargo test -j 1 --workspace --doc"            > /tmp/root.log
#   ./dev.sh run "cd /work/crates/wiremesh-enforcer-ebpf && cargo test -j 1 --doc" > /tmp/ebpf.log
#   dev/doctest-counts.sh generate /tmp/root.log /tmp/ebpf.log > dev/doctest-counts.txt
set -euo pipefail

TABLE="$(dirname "$0")/doctest-counts.txt"

usage() { echo "usage: dev/doctest-counts.sh {generate|check} <root-doc-log> <ebpf-doc-log>" >&2; exit 2; }
[ $# -eq 3 ] || usage
mode=$1; root_log=$2; ebpf_log=$3
[ -r "$root_log" ] || { echo "doctest-counts: cannot read $root_log" >&2; exit 2; }
[ -r "$ebpf_log" ] || { echo "doctest-counts: cannot read $ebpf_log" >&2; exit 2; }

# `Doc-tests <crate>` then, some lines later, `test result: ok. N passed; N
# failed; N ignored; ...`. Emit `<crate> passed=<n> failed=<n> ignored=<n>`,
# sorted, so the table is order-independent and diffs cleanly.
parse() {
  awk '
    /^[[:space:]]*Doc-tests /      { crate=$2; next }
    /^test result:/ && crate != "" {
      p=f=i=0
      for (k = 1; k <= NF; k++) {
        if ($(k+1) ~ /^passed/)  p=$k
        if ($(k+1) ~ /^failed/)  f=$k
        if ($(k+1) ~ /^ignored/) i=$k
      }
      printf "%s passed=%d failed=%d ignored=%d\n", crate, p, f, i
      crate=""
    }
  ' "$1"
}

emit() { { parse "$root_log"; parse "$ebpf_log"; } | sort; }

case "$mode" in
  generate)
    echo "# GENERATED by dev/doctest-counts.sh — do not hand-edit."
    echo "# The per-crate doctest inventory. A difference here means a doctest"
    echo "# APPEARED or VANISHED; see that script's header for why both are bugs."
    echo "# Regenerate deliberately, from a real run, when the change is intended."
    emit
    ;;
  check)
    [ -r "$TABLE" ] || { echo "doctest-counts: $TABLE is missing — generate it from a real run" >&2; exit 1; }
    if diff -u <(grep -v '^#' "$TABLE" | sed '/^$/d') <(emit); then
      echo "doctest inventory unchanged"
    else
      echo "::error::the doctest inventory changed. A doctest APPEARED or VANISHED." >&2
      echo "::error::An appearance is usually prose that rustdoc started compiling (a" >&2
      echo "::error::closed Markdown list turns an indented paragraph into a code block)." >&2
      echo "::error::A disappearance is a LOST TEST. Fix the cause; if the change is" >&2
      echo "::error::intended, regenerate dev/doctest-counts.txt from a real run." >&2
      exit 1
    fi
    ;;
  *) usage ;;
esac
